const React = require('react')
const Def = require('./default.jsx')

function home() {
    return (
        <Def>
            <main>
                <h1>REST-Rant</h1>
                <div>
                    <img src="/images/rest-rant.png" alt="rest-rant picture" />
                    <div>
                        <p>Photo is AI generated by <a href="https:midjourney.com">Midjourney</a></p>
                    </div>
                </div>
                <a href="/places">
                    <button className="btn btn-primary btn-lg">Places Page</button>
                </a>
            </main>
        </Def>
    )
}

module.exports = home